export enum Events {
  POST_CREATION_STARTED = "Post creation started",
  CLICKED_ON_ATTACHMENT = "Clicked on Attachment",
  USER_TAGGED_IN_POST = "User tagged in a post",
  LINK_ATTACHED_IN_POST = "link attached in the post",
  IMAGE_ATTACHED_TO_POST = "Image attached to post",
  VIDEO_ATTACHED_TO_POST = "Video attached to post",
  DOCUMENT_ATTACHED_TO_POST = "Document attached in post",
  POST_CREATION_COMPLETED = "Post creation completed",
  POST_PINNED = "Post pinned",
  POST_UNPINNED = "Post unpinned",
  POST_REPORTED = "Post reported",
  POST_DELETED = "Post deleted",
  FEED_OPENED = "Feed opened",
  LIKE_LIST_OPEN = "Like list open",
  COMMENT_LIST_OPEN = "Comment list open",
  COMMENT_DELETED = "Comment deleted",
  COMMENT_REPORTED = "Comment reported",
  COMMENT_POSTED = "Comment posted",
  REPLY_POSTED = "Reply posted",
  REPLY_DELETED = "Reply deleted",
  REPLY_REPORTED = "Reply reported",
  POST_EDITED = "Post edited",
  POST_SHARED = "Post shared",
  POST_LIKED = "Post Liked",
  POST_UNLIKED = "Post Unliked",
  POST_SAVED = "Post Saved",
  POST_UNSAVED = "Post Unsaved",
  COMMENT_LIKED = "Comment Liked",
  COMMENT_UNLIKED = "Comment Unliked",
  COMMENT_EDITED = "Comment edited",

  NOTIFICATION_RECEIVED = "Notification Received",
  NOTIFICATION_CLICKED = "Notification Clicked",

  NOTIFICATION_PAGE_OPENED = "Notification page opened",
}
