export enum ScreenNames {
  UNIVERSAL_FEED = "universalFeed",
  FEED_ROOM = "feedroom",
  POST_DETAIL_SCREEN = "postDetailScreen",
  USER_FEED = "userFeed",
  ACTIVITY_SCREEN = "activityScreen",
  CREATE_POST_SCREEN = "createPostScreen",
  EDIT_POST_SCREEN = "editPostScreen",
  NOTIFICATION_SCREEN = "notificationScreen",
  TOPIC_SELECT_SCREEN = "topicSelectScreen",
  LIKES_SCREEN = "likesScreen",
  MEDIA_PREVIEW_SCREEN = "mediaPreviewScreen",
  REPORT_SCREEN = "reportScreen",
  SEARCH_SCREEN = "searchScreen",
  SAVED_POST_SCREEN = "savedPostScreen",
  USER_CREATED_COMMENT_SCREEN = "userCreatedCommentScreen",
  USER_PROFILE_SCREEN = "userProfileScreen",
  TOPIC_DETAIL_SCREEN = "topicDetailScreen",
  OTHER = "other",
}
