pipeline {
    agent {label 'localMachine'}
    tools {nodejs "nodejs"}

    options {
        buildDiscarder logRotator(daysToKeepStr: '3', numToKeepStr: '1')
    }
    parameters {
        stashedFile 'FILE'
        stashedFile 'FILE_SECOND'
    }
    stages {

        stage('check'){
            steps{
                dir('likeminds-feed-reactnative-integration'){
                    sh "ls"
                }
            }
        }

        stage('file upload'){
            steps{
                dir('likeminds-feed-reactnative-integration'){
                    unstash 'FILE'
                    unstash 'FILE_SECOND'
                    sh 'mv FILE $FILE_FILENAME'
                    sh 'mv FILE_SECOND $FILE_SECOND_FILENAME'
                    sh 'ls'
                }
            }
        }
        
        
        // stage('Install Dependencies') {
        //     steps {
        //         sh 'npm install'
        //     }
        // }

        // stage('Build') {
        //     steps {
        //         sh 'npm run build'
        //     }
        // }

        // stage('Package') {
        //     steps {
        //         sh 'npm pack'
        //     }
        // }

        // stage('Archive Package') {
        //     steps {
        //         archiveArtifacts artifacts: '*.tgz', fingerprint: true
        //     }
        // }
    }

}