pipeline {
    agent any
    tools {nodejs "nodejs"}

    options {
        buildDiscarder logRotator(daysToKeepStr: '7', numToKeepStr: '1')
    }
    parameters {
        stashedFile 'feed_rn_package'
    }
    stages {

        stage('check'){
            steps{
                dir('likeminds-feed-reactnative-integration'){
                    sh "ls"
                }
            }
        }

        stage('file upload'){
            steps{
                dir('likeminds-feed-reactnative-integration'){
                    unstash 'feed_rn_package'
                    sh 'mv feed_rn_package $feed_rn_package_FILENAME'
                    sh 'ls'
                }
            }
        }
        
        
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Package') {
            steps {
                sh 'npm pack'
            }
        }

        stage('Archive Package') {
            steps {
                dir('likeminds-feed-reactnative-integration'){
                    archiveArtifacts artifacts: '*.tgz', fingerprint: true
                }
            }
        }
    }
    
    post{
        always{
            cleanWs()
        }
    }

}